#! /bin/bash

./Client < student-tests/1-in.json | diff - student-tests/1-out.json`	
./Client < student-tests/2-in.json | diff - student-tests/2-out.json`	
./Client < student-tests/3-in.json | diff - student-tests/3-out.json`	
./Client < student-tests/4-in.json | diff - student-tests/4-out.json`	

